### ISSUE TITLE
IPv6 Support

### ISSUE THREAD

**Issue by marcelkaus** [VRT-onderzoek-en-innovatie/tcp-intercept#12]
I've tried to run tcp-intercept with IPv6.

I changed /etc/default/tcp-intercept so that its listening on IPv6 sockets:

#BIND_LISTEN="[0.0.0.0]:[5000]"
#BIND_OUTGOING="[0.0.0.0]:[0]"
BIND_LISTEN=":::5000"
BIND_OUTGOING=":::*"

When the service is running netstats also shows that it is listening on IPv6 TCP socket 5000
I've also did some changes to iptables and ip rules:

IP_ROUTE_TABLE_NUMBER=6 # free routing table number to use
FWMARK="0x01/0x01" # Distinguishing FWmark bit to use
LISTEN_PORT=5000 # Port where tcp-intercept is listening on
ip -6 rule add fwmark $FWMARK table $IP_ROUTE_TABLE_NUMBER
ip -6 route add local ::/0 dev lo table $IP_ROUTE_TABLE_NUMBER
ip6tables -t mangle -N tproxy
ip6tables -t mangle -A tproxy -p tcp -m socket -j MARK --set-mark $FWMARK
ip6tables -t mangle -A tproxy -p tcp -m socket -j RETURN
ip6tables -t mangle -A tproxy -p tcp -m addrtype --dst-type LOCAL -j RETURN
ip6tables -t mangle -A tproxy -p tcp -j TPROXY \
                   --on-port $LISTEN_PORT --tproxy-mark $FWMARK
ip6tables -t mangle -A PREROUTING -j tproxy

Incoming TCP connections to the proxy server are accepted but the proxy doesn't create a new outgoing connection to the destination. Some data is transmitted but only to the point where the buffer is full, then its stops.

Is there something wrong with the configuration or is the proxy not IPv6 capable?

**Comment by nielslaukens** [comment]
Hi, thank you for the bug report.

I've done my best to code `tcp-intercept` protocol-agnostic as to support both IPv4 and IPv6. However, I don't have access to a functional IPv6 network to test that.

Are you willing and able to do part of the debugging yourself? I'd gladly help to guide you through the process, but without a testing ground it's hard to debug things.

**Comment by marcelkaus** [comment]
Sure. I could do the debugging by myself.

Right now my test setup consists of several virtual machines that are connected to each other. But as far as i'm concerned this should translate to a real world scenario.

**Comment by nielslaukens** [comment]
could you start by providing the log output of a test which shows what you are trying to accomplish?

**Comment by marcelkaus** [comment]
Log Files shows me 

2015-01-21T14:34:35.507284+0100 tcp-intercept version 1.0.2 (v1.0.1-4-gb7279bc) starting up
2015-01-21T14:34:35.508233+0100 Listening on [::]:5000
2015-01-21T14:34:35.508356+0100 Outgoing connections will connect from [::]:0
2015-01-21T14:34:35.510260+0100 Setup done, starting event loop
2015-01-21T14:35:47.060337+0100 [192:168::10]:56325-->[10:1::2]:5001: Connection intercepted
2015-01-21T14:35:47.061888+0100 Error: Could not bind: Address family not supported by protocol

**Comment by marcelkaus** [comment]
i just had a look into the code and was wondering... when we open a new socket at the proxy we do something like 

new_con->s_server = Socket::socket(AF_INET, SOCK_STREAM, 0);

shouldn't i look like 

new_con->s_server = Socket::socket(AF_INET6, SOCK_STREAM, 0);

if we want to use an IPv6 address

**Comment by nielslaukens** [comment]
Good find! And (to my own surprise) it's even a <a href="https://github.com/VRT-onderzoek-en-innovatie/tcp-intercept/blob/master/src/tcp-intercept.cxx#L266">documented</a> bug...

Anyway, can you check the updated version?

**Comment by marcelkaus** [comment]
I've tested the changes. Still the same.

I tried to debug the binary with gdb but the debian package that i build with dpkg-buildpackage doesnt include debug symbols somehow.
How do i compile the source with debug symbols?

**Comment by nielslaukens** [comment]
You can follow the instructions in the README, but use

    CFLAGS="-g -O0" CXXFLAGS="-g -O0" ./configure

for the configure command. That will enable debug symbols, and disable optimization. You don't need to run the `make install` part if you run the `tcp-intercept` command by hand (i.e. not via the init script) for the duration of the tests.

**Comment by marcelkaus** [comment]
Never mind it seemed that i screwed up when building the package.
Your Changes are working.
