### ISSUE TITLE
question about NAT support

### ISSUE THREAD

**Issue by chrpinedo** [VRT-onderzoek-en-innovatie/tcp-intercept#13]
I have a question about NAT support with the current iptables scripts. Do these iptables-scripts support DNAT and SNAT configuration with iptables??? I'm supposing that the tcp-intercept software is run in a gateway connected to Internet and providing connectivity to an internal private network. Thanks,

Christian

**Comment by nielslaukens** [comment]
Hi Christian,

I'm not sure I understand your question correctly, so feel free to elaborate if I did not answer it.

The iptables-snippet in the README does not do any NAT, but you can add your own NAT-rules beside them, if you want to. If you want to use `tcp-intercept` between clients on your private network, and your internet connections, you can also use the `--bind-outgoing` option. If you specify (one of) your public addresses here, `tcp-intercept` will effectively do (S)NAT as part of the intercept-process.  (Note that it will only (S)NAT traffic that it intercepts, thus you still need iptables-rules for non-TCP traffic)

**Comment by chrpinedo** [comment]
Hello,

I would try to explain better... I would like to apply the tcp-intercept in a NAT-router: one internal network with private addresses and one WAN (Internet) connection with a public IP address.

From my understanding, the outgoing traffic towards WAN is going to work fine with the current iptables-snippet. The snippet detects that the destination address of an internal computer is different and forwards the TCP connection to the tcp-intercept program. From now on, the tcp-intercept program stablishes new MPTCP connections.

However, I think that there is a problem with new incoming MPTCP connections from WAN. For example, let's suppose that NAT-router with tcp-intercept forwards the port TCP/80 to the internal IP address 192.168.1.23. In that case, the iptables-snippet thinks that the packet is directed to the NAT-router itself because the translation from destination public address to destination private address is performed in the NAT PREROUTING chain that is called later than MANGLE PREROUTING (http://www.linuxhomenetworking.com/wiki/images/f/f0/Iptables.gif). Thus, this MPTCP traffic wouldn't be intercepted and would pass seamless to the 192.168.1.23 IP address.

**Comment by nielslaukens** [comment]
You are correct that `mangle` is performed before `nat`. In your case, you would need to alter the `mangle` table so that it still sends the to-be-DNAT-ed packets to `tcp-intercept`. Once these packets travel through the `nat` table, you can perform the DNAT you want, and normally (untested) `tcp-intercept` should see the new destination address and carry on.

**Comment by chrpinedo** [comment]
I performed some tests.

Current firewall rules are valid for outgoing NAT (source NAT). Outgoing connections are intercepted and redirected to the tcp-intercept program.

However, for incomming new TCP connections redirected to internal IP addresses and TCP ports (destination NAT) the TCP connection is redirected to the internal IP-address/TCP-port without being intercepted by the tcp-intercfept program. To allow it, I have changed the firewall configuration in the init script (this could be changed in your github code and include instructions about the NAT usage, if you consider it useful):

```bash
iptables -t mangle -N tproxy 2>/dev/null
iptables -t mangle -N tproxy-dnat 2>/dev/null
iptables -t mangle -F tproxy
iptables -t mangle -A tproxy -p tcp -m socket -j MARK --set-mark $FWMARK
iptables -t mangle -A tproxy -p tcp -m socket -j RETURN
iptables -t mangle -A tproxy -j tproxy-dnat
iptables -t mangle -A tproxy -p tcp -m addrtype --dst-type LOCAL -j RETURN
iptables -t mangle -A tproxy -p tcp -j TPROXY --on-port $LISTEN_PORT \
    --tproxy-mark $FWMARK
if ! iptables -t mangle -nL PREROUTING | grep tproxy >/dev/null; then
    iptables -t mangle -A PREROUTING -j tproxy
fi
```
Now if I want to redirect one TCP port (Destination NAT):

1. Configure the DNAT:
```bash
iptables -t nat -A PREROUTING -i eth1 -p tcp --dport 80 -j DNAT --to-destination 192.168.1.23
```
2. Now DNAT is configured but the incomming TCP connection is not intercepted 
3. To allow TCP interception:
```bash
iptables -t mangle -A tproxy-dnat -i eth1 -p tcp --dport 80 -j TPROXY --on-port 5000 --tproxy-mark 0x1/0x1
```
