### ISSUE TITLE
caonfigure script not avaliable

### ISSUE THREAD

**Issue by andreykyz** [VRT-onderzoek-en-innovatie/tcp-intercept#14]
Hello. I try to touch your program as tcp to mptcp converter. But you don't add configure script to a repo. I try to generate myself configure script, but can't:
<pre>
andrey@andrey-ThinkPad-L520:~/sandbox/tcp-intercept$ autoconf
configure.ac:3: error: possibly undefined macro: AM_INIT_AUTOMAKE
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:38: error: possibly undefined macro: AM_PROG_CC_C_O
configure.ac:39: error: possibly undefined macro: AM_GNU_GETTEXT_VERSION
configure.ac:40: error: possibly undefined macro: AM_GNU_GETTEXT
configure.ac:109: error: possibly undefined macro: AS_AC_EXPAND
andrey@andrey-ThinkPad-L520:~/sandbox/tcp-intercept$ ./configure
./configure: line 2250: syntax error near unexpected token `foreign'
./configure: line 2250: `AM_INIT_AUTOMAKE(foreign dist-bzip2 -Wall)'
</pre>
May be I use wrong autoconf-2.69, can you help me?

**Comment by nielslaukens** [comment]
Do you have `automake` installed?
Either way, I've created [a tarball](https://github.com/VRT-onderzoek-en-innovatie/tcp-intercept/releases/download/v1.0.2/tcp-intercept-1.0.2.tar.bz2) which should have a working `./configure` script inside here:

**Comment by nielslaukens** [comment]
No feedback within (almost) a year. Closing...
