### ISSUE TITLE
Resource leakage.

### ISSUE THREAD

**Issue by maedot-d** [VRT-onderzoek-en-innovatie/tcp-intercept#15]
Hi Niels,
I have been testing tcp-intercept for a while now on a router at home. Performance wise it works very good but resource utilisation is not optimal. There is resource leakage, that is, there are may connections that hang on CLOSE_WAIT, or FIN_WAIT2, or ESTABLISHED states. I have investigated the cause of this problem and found out that tcp-intercept has no mechanism to track such scenarios and take care of them.

Root cause of the problem is that, if one end of the connection sends a FIN to the opposite side, which is not there to reply (unreachable) for any reason, then the connection in tcp-intercept will hang. The side that received the FIN will go to CLOSE_WAIT state while the other end which expects the FIN_ACK goes to FIN_WAIT state. This is one lock-up state which accumulates in time and consumes a considerable amount of file descriptors (could even block making new connections for heavy users in a very short period of time). My first approach to solve this problem was increasing the file descriptor size and regularly restarting tcp-intercept, but that was just treating the symptoms and was not the way to go!

Second problem is the established state. After a successful connection, if one of the peers disappears without feedback to the other peer (especially the one that has no data to send), then the connection hangs in this state forever. And again this leads to the same problem as above.

These two scenarios are common phenomenon in a day to day life. Users simply close their laptops and move on, smartphones get out of AP reach, applications are hard killed, or many other similar situations that lead to one peer disappearing without feedback to tcp-intercept. 

To address these issues, I have added some features to tcp-intercept: track connections that used shutdown() function and force close them after a time out, and add keepalive socket option (on the server side) to handle established state problem. I have been testing this for a few days now, and so far I have seen no file descriptor issues nor have I seen such hanging connections with netstat.

I can gladly send you the changes to patch your version.

Cheers!
Maedot

**Comment by nielslaukens** [comment]
Hi Maedot,

Very nice analysis of the problem. You are indeed correct that tcp-intercept does no active connection checking itself. When facing unreliable networks, this may indeed cause the problems you describe.

I'd gladly review any patches you may have and consider them for inclusion here.

N

**Comment by ramabeec** [comment]
Hi Maedot 

I was able to generate FIN_WAIT2 on the machine where tcp-intercept runs(on the router). After ~5 mins, I don't see the number of FIN_WAIT2 is decreasing (but this is observed with and without tcp-intercept option -k and -n ) Please let me know how did you reproduce the issue and test your patch. Also how fast this patch will close the FIN_WAIT2 sockets.

I use ab(apache benchmarking) to generate the FIN_WAIT2 on the router by running "ab -n 500000 -c 500 http://speedtest.wdc01.softlayer.com/downloads/test100.zip" on the client and then shut down it after 40 seconds.

net.ipv4.tcp_low_latency = 1 when -k and -n are used

**Comment by maedot-d** [comment]
Hi,

You would have to reproduce the problem to see the effects of my patch. To 
do so, you need to drop FIN_ACKs using iptables. Then use a tool to see 
your active/open sockets (netstat or even a better one 
http://veithen.github.io/2013/12/19/inspecting-socket-options-on-linux.html). 
You should be able to see sockets hanging in the FIN_WAIT / CLOSE_WAIT 
states.

Hope this helps.

Cheers!
Maedot

-----Original-Nachricht-----
Von: ramabeec <notifications@github.com <mailto:notifications@github.com> 
>
Betreff: Re: [VRT-onderzoek-en-innovatie/tcp-intercept] Resource leakage. 
(#15)
Datum: 13.05.2017, 09:50 Uhr
An: VRT-onderzoek-en-innovatie/tcp-intercept <
tcp-intercept@noreply.github.com <mailto:tcp-intercept@noreply.github.com> 
>
CC: maedot-d <maedot@t-online.de <mailto:maedot@t-online.de> >, Author <
author@noreply.github.com <mailto:author@noreply.github.com> >

Hi Maedot

I was able to generate FIN_WAIT2 on the machine where tcp-intercept runs(on 
the router). After ~5 mins, I don't see the number of FIN_WAIT2 is 
decreasing but after ~10 mins all FIN_WAIT2 were closed(but this is 
observed with and without tcp-intercept option -k and -n ) Please let me 
know how did you reproduce the issue and test your patch. Also how fast 
this patch will close the FIN_WAIT2 sockets.

I use ab(apache benchmarking) to generate the FIN_WAIT2 on the router by 
running "ab -n 500000 -c 500 
http://speedtest.wdc01.softlayer.com/downloads/test100.zip
<http://speedtest.wdc01.softlayer.com/downloads/test100.zip> " on the 
client and then shut down it after 40 seconds.

net.ipv4.tcp_low_latency = 1 when -k and -n are used

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/VRT-onderzoek-en-innovatie/tcp-intercept/issues/15#issuecomment-301232290> 
, or mute the thread

**Comment by ramabeec** [comment]
Hi Maedot-d,

Thank you for quick response.

We are having issue of Too Many file open so , the setup we made to verify that has bellow

Laptop<--->VM1<--->VM2

Laptop Setting : 
1. Installed with {Kubuntu 14.04} with KTorrent
2. Default route set to VM1

VM1 and VM2 Setting:
1. VM1 and VM2 installed with tcp-intercept (version 1.1.1) and run with -k option
2. VM1 Defualt route set to VM2
3. Set sysctl variables for both VM1 and VM2 are
   sudo sysctl -w net.ipv4.tcp_keepalive_time=1200
   sudo sysctl -w net.ipv4.tcp_tw_reuse=1
   sudo sysctl -w net.ipv4.tcp_fin_timeout=30
   
We used KTorrent to download 12 torrent file from ubuntu distro https://www.ubuntu.com/download/alternative-downloads.
So we started KTorrent and wait for 2 minutes then using 'stop all' button we stopped the ktorrent to download.

Then we notice following on  VM1 and VM2 :
If any of the tcp states {viewed with netstat} are greater than 700 , 
then we found "Too Many file open error on TCP-Intercept log"
So, we are not able to establish new connections.

Can i know how you optimised your router with tcp-intercept to allow large number of connections 

Regards,
Ramakrishna

**Comment by maedot-d** [comment]
Hi Ramakrishna,

Sorry for the late reply, I just came back from a travel.
It seems you are having the exact problem I tried to solve for 
tcp-intercept at the beginning. It is running out of resources (file 
descriptors). When it reaches the system default size, it stops making new 
connections. To solve this you need to increase this size in your system. A 
description of your project goal would help to give you a helpful advice.

Cheers!
Maedot

-----Original-Nachricht-----
Von: VRamakrishnaYenumala <notifications@github.com
<mailto:notifications@github.com> >
Betreff: Re: [VRT-onderzoek-en-innovatie/tcp-intercept] Resource leakage. 
(#15)
Datum: 09.06.2017, 16:48 Uhr
An: VRT-onderzoek-en-innovatie/tcp-intercept <
tcp-intercept@noreply.github.com <mailto:tcp-intercept@noreply.github.com> 
>
CC: maedot-d <maedot@t-online.de <mailto:maedot@t-online.de> >, Author <
author@noreply.github.com <mailto:author@noreply.github.com> >

Hi Maedot-d,

Thank you for quick response.

We are having issue of Too Many file open so , the setup we made to verify 
that has bellow

Laptop<--->VM1<--->VM2

Laptop Setting :

   1. Installed with {Kubuntu 14.04} with KTorrent
   2. Default route set to VM1

VM1 and VM2 Setting:

   1. VM1 and VM2 installed with tcp-intercept (version 1.1.1) and run with
      -k option
   2. VM1 Defualt route set to VM2
   3. Set sysctl variables for both VM1 and VM2 are
      sudo sysctl -w net.ipv4.tcp_keepalive_time=1200
      sudo sysctl -w net.ipv4.tcp_tw_reuse=1
      sudo sysctl -w net.ipv4.tcp_fin_timeout=30

We used KTorrent to download 12 torrent file from ubuntu distro 
https://www.ubuntu.com/download/alternative-downloads
<https://www.ubuntu.com/download/alternative-downloads> .
So we started KTorrent and wait for 2 minutes then using 'stop all' button 
we stopped the ktorrent to download.

Then we notice following on VM1 and VM2 :
If any of the tcp states {viewed with netstat} are greater than 700 ,
then we found "Too Many file open error on TCP-Intercept log"
So, we are not able to establish new connections.

Can i know how you optimised your router with tcp-intercept to allow large 
number of connections

Regards,
Ramakrishna

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/VRT-onderzoek-en-innovatie/tcp-intercept/issues/15#issuecomment-307409403> 
, or mute the thread
